services:
  hub:
    image: selenium/hub:4.32
  chrome:
    image: selenium/node-chromium:4.32
    shm_size: "1g"
    deploy:
      replicas: 0
    depends_on:
      - hub
    env_file:
      - .env
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: "1g"
    deploy:
      replicas: 0
    depends_on:
      - hub
    env_file:
      - .env
